export const FETCH_RULES_START = 'FETCH_RULES_START';
export const FETCH_RULES_SUCCESS = 'FETCH_RULES_SUCCESS';
export const FETCH_RULES_FAIL = 'FETCH_RULES_FAIL';

export const SHOW_RULE_DETAILS = 'SHOW_RULE_DETAILS';