export const FETCH_RULES_START = 'FETCH_RULES_START';
export const FETCH_RULES_SUCCESS = 'FETCH_RULES_SUCCESS';
export const FETCH_RULES_FAIL = 'FETCH_RULES_FAIL';

export const FETCH_COLUMN_DATA_START = 'FETCH_COLUMN_DATA_START';
export const FETCH_COLUMN_DATA_SUCCESS = 'FETCH_COLUMN_DATA_SUCCESS';
export const FETCH_COLUMN_DATA_FAIL = 'FETCH_COLUMN_DATA_FAIL';

export const SHOW_RULE_DETAILS = 'SHOW_RULE_DETAILS';

export const CHANGE_SELECTED_AMOUNT = 'CHANGE_SELECTED_AMOUNT';

export const SORT_RULE_TABLE = 'SORT_RULE_TABLE';

export const SELECT_ALL_RULES = 'SELECT_ALL_RULES';