export const FETCH_RULES_START = 'FETCH_RULES_START';
export const FETCH_RULES_SUCCESS = 'FETCH_RULES_SUCCESS';
export const FETCH_RULES_FAIL = 'FETCH_RULES_FAIL';

export const FETCH_TRANSACTIONS_START = 'FETCH_TRANSACTIONS_START';
export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_TRANSACTIONS_FAIL = 'FETCH_TRANSACTIONS_FAIL';

export const FETCH_COLUMN_DATA_START = 'FETCH_COLUMN_DATA_START';
export const FETCH_COLUMN_DATA_SUCCESS = 'FETCH_COLUMN_DATA_SUCCESS';
export const FETCH_COLUMN_DATA_FAIL = 'FETCH_COLUMN_DATA_FAIL';

export const SHOW_RULE_DETAILS = 'SHOW_RULE_DETAILS';

export const CHANGE_SELECTED_RULE_AMOUNT = 'CHANGE_SELECTED_RULE_AMOUNT';
export const CHANGE_SELECTED_TRANSACTION_AMOUNT = 'CHANGE_SELECTED_TRANSACTION_AMOUNT';

export const SORT_RULE_TABLE = 'SORT_RULE_TABLE';
export const SORT_TRANSACTION_TABLE = 'SORT_TRANSACTION_TABLE';

export const SELECT_ALL_RULES = 'SELECT_ALL_RULES';
export const SELECT_ALL_TRANSACTIONS = 'SELECT_ALL_TRANSACTIONS';

export const FILTER_TRANSACTIONS_START = 'FILTER_TRANSACTIONS_START';
export const FILTER_TRANSACTIONS_SUCCESS = 'FILTER_TRANSACTIONS_SUCCESS';
export const FILTER_TRANSACTIONS_FAIL = 'FILTER_TRANSACTIONS_FAIL';

